# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreditCardInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, number: str=None):  # noqa: E501
        """CreditCardInfo - a model defined in Swagger

        :param id: The id of this CreditCardInfo.  # noqa: E501
        :type id: int
        :param number: The number of this CreditCardInfo.  # noqa: E501
        :type number: str
        """
        self.swagger_types = {
            'id': int,
            'number': str
        }

        self.attribute_map = {
            'id': 'id',
            'number': 'number'
        }

        self._id = id
        self._number = number

    @classmethod
    def from_dict(cls, dikt) -> 'CreditCardInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The credit_card_info of this CreditCardInfo.  # noqa: E501
        :rtype: CreditCardInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this CreditCardInfo.


        :return: The id of this CreditCardInfo.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this CreditCardInfo.


        :param id: The id of this CreditCardInfo.
        :type id: int
        """

        self._id = id

    @property
    def number(self) -> str:
        """Gets the number of this CreditCardInfo.


        :return: The number of this CreditCardInfo.
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number: str):
        """Sets the number of this CreditCardInfo.


        :param number: The number of this CreditCardInfo.
        :type number: str
        """

        self._number = number
