---
swagger: "2.0"
info:
  description: "Groupe 3"
  version: "1.0.0"
  title: "Payment module"
  license:
    name: "Github"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "non_defini"
basePath: "/resource"
tags:
- name: "payment"
  description: "Payment module"
schemes:
- "http"
paths:
  /payments:
    post:
      tags:
      - "payments"
      summary: "Request payments"
      description: ""
      operationId: "make_payments"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Request a payments"
        required: true
        schema:
          $ref: "#/definitions/Payment"
      responses:
        "202":
          description: "In traitment"
          schema:
            $ref: "#/definitions/ApiReturn"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.payments_controller"
definitions:
  credit_card_info:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      number:
        type: "string"
    example:
      number: "number"
      id: 6
  buyer_info:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    example:
      name: "name"
      id: 0
  Payment:
    type: "object"
    required:
    - "buyer_info"
    - "checkout_id"
    properties:
      buyer_info:
        $ref: "#/definitions/buyer_info"
      checkout_id:
        type: "string"
      credit_card_info:
        $ref: "#/definitions/credit_card_info"
      payment_orders:
        type: "array"
        items:
          type: "string"
      seller_account:
        type: "string"
      amount:
        type: "string"
      currency:
        type: "string"
        format: "ISO 4217"
      payment_order_id:
        type: "string"
    example:
      checkout_id: "checkout_id"
      amount: "amount"
      payment_orders:
      - "payment_orders"
      - "payment_orders"
      buyer_info:
        name: "name"
        id: 0
      currency: "currency"
      credit_card_info:
        number: "number"
        id: 6
      seller_account: "seller_account"
      payment_order_id: "payment_order_id"
  ApiReturn:
    type: "object"
    properties:
      code:
        type: "integer"
      message:
        type: "string"
    example:
      code: 0
      message: "message"
